name: "Formulaire de réinitialisation du mot de passe"
multiple: FALSE
category: 'Espace privé'
enabled: TRUE
fields:
  title:
    type: text
    label: "Titre"
  intro:
    type: text_format
    label: 'Introduction'
    options:
      '#format': 'full_html'